//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 02:54:20 PM MESZ 
//


package module;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ct_beschreibung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_beschreibung">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dozent">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="dozentId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lerninhalte">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="punkt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lernmethode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voraussetzungen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="veranstaltungsort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_beschreibung", propOrder = {
    "dozent",
    "lerninhalte",
    "lernmethode",
    "voraussetzungen",
    "veranstaltungsort"
})
public class CtBeschreibung {

    @XmlElement(required = true)
    protected CtBeschreibung.Dozent dozent;
    @XmlElement(required = true)
    protected CtBeschreibung.Lerninhalte lerninhalte;
    @XmlElement(required = true)
    protected String lernmethode;
    @XmlElement(required = true)
    protected String voraussetzungen;
    @XmlElement(required = true)
    protected String veranstaltungsort;

    /**
     * Gets the value of the dozent property.
     * 
     * @return
     *     possible object is
     *     {@link CtBeschreibung.Dozent }
     *     
     */
    public CtBeschreibung.Dozent getDozent() {
        return dozent;
    }

    /**
     * Sets the value of the dozent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBeschreibung.Dozent }
     *     
     */
    public void setDozent(CtBeschreibung.Dozent value) {
        this.dozent = value;
    }

    /**
     * Gets the value of the lerninhalte property.
     * 
     * @return
     *     possible object is
     *     {@link CtBeschreibung.Lerninhalte }
     *     
     */
    public CtBeschreibung.Lerninhalte getLerninhalte() {
        return lerninhalte;
    }

    /**
     * Sets the value of the lerninhalte property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBeschreibung.Lerninhalte }
     *     
     */
    public void setLerninhalte(CtBeschreibung.Lerninhalte value) {
        this.lerninhalte = value;
    }

    /**
     * Gets the value of the lernmethode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLernmethode() {
        return lernmethode;
    }

    /**
     * Sets the value of the lernmethode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLernmethode(String value) {
        this.lernmethode = value;
    }

    /**
     * Gets the value of the voraussetzungen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoraussetzungen() {
        return voraussetzungen;
    }

    /**
     * Sets the value of the voraussetzungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoraussetzungen(String value) {
        this.voraussetzungen = value;
    }

    /**
     * Gets the value of the veranstaltungsort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVeranstaltungsort() {
        return veranstaltungsort;
    }

    /**
     * Sets the value of the veranstaltungsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVeranstaltungsort(String value) {
        this.veranstaltungsort = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="dozentId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Dozent {

        @XmlValue
        protected String value;
        @XmlAttribute
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger dozentId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the dozentId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDozentId() {
            return dozentId;
        }

        /**
         * Sets the value of the dozentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDozentId(BigInteger value) {
            this.dozentId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="punkt" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "punkt"
    })
    public static class Lerninhalte {

        protected List<String> punkt;

        /**
         * Gets the value of the punkt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the punkt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPunkt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPunkt() {
            if (punkt == null) {
                punkt = new ArrayList<String>();
            }
            return this.punkt;
        }

    }

}
