//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.29 at 01:49:34 PM MESZ 
//


package module;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the module package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: module
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtBeschreibung }
     * 
     */
    public CtBeschreibung createCtBeschreibung() {
        return new CtBeschreibung();
    }

    /**
     * Create an instance of {@link Modul.Bezeichnung }
     * 
     */
    public Modul.Bezeichnung createModulBezeichnung() {
        return new Modul.Bezeichnung();
    }

    /**
     * Create an instance of {@link Modul }
     * 
     */
    public Modul createModul() {
        return new Modul();
    }

    /**
     * Create an instance of {@link CtAbonnenten }
     * 
     */
    public CtAbonnenten createCtAbonnenten() {
        return new CtAbonnenten();
    }

    /**
     * Create an instance of {@link CtBeschreibung.Lerninhalte }
     * 
     */
    public CtBeschreibung.Lerninhalte createCtBeschreibungLerninhalte() {
        return new CtBeschreibung.Lerninhalte();
    }

}
