//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.17 at 10:44:54 AM MESZ 
//


package jaxb.modulliste;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mEintrag" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="zustand" type="{}st_zustand"/>
 *                   &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="modulId" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mEintrag"
})
@XmlRootElement(name = "modulliste")
public class Modulliste {

    protected List<Modulliste.MEintrag> mEintrag;

    /**
     * Gets the value of the mEintrag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mEintrag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEintrag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modulliste.MEintrag }
     * 
     * 
     */
    public List<Modulliste.MEintrag> getMEintrag() {
        if (mEintrag == null) {
            mEintrag = new ArrayList<Modulliste.MEintrag>();
        }
        return this.mEintrag;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="zustand" type="{}st_zustand"/>
     *         &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="modulId" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zustand",
        "bezeichnung"
    })
    public static class MEintrag {

        @XmlElement(required = true)
        protected StZustand zustand;
        @XmlElement(required = true)
        protected String bezeichnung;
        @XmlAttribute
        protected BigInteger modulId;

        /**
         * Gets the value of the zustand property.
         * 
         * @return
         *     possible object is
         *     {@link StZustand }
         *     
         */
        public StZustand getZustand() {
            return zustand;
        }

        /**
         * Sets the value of the zustand property.
         * 
         * @param value
         *     allowed object is
         *     {@link StZustand }
         *     
         */
        public void setZustand(StZustand value) {
            this.zustand = value;
        }

        /**
         * Gets the value of the bezeichnung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBezeichnung() {
            return bezeichnung;
        }

        /**
         * Sets the value of the bezeichnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBezeichnung(String value) {
            this.bezeichnung = value;
        }

        /**
         * Gets the value of the modulId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getModulId() {
            return modulId;
        }

        /**
         * Sets the value of the modulId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setModulId(BigInteger value) {
            this.modulId = value;
        }

    }

}
