//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.26 at 07:21:10 PM MESZ 
//


package studenten;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_abos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_abos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="module" type="{}ct_modul"/>
 *         &lt;element name="dozent" type="{}ct_dozent"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_abos", propOrder = {
    "module",
    "dozent"
})
public class CtAbos {

    @XmlElement(required = true)
    protected CtModul module;
    @XmlElement(required = true)
    protected CtDozent dozent;

    /**
     * Gets the value of the module property.
     * 
     * @return
     *     possible object is
     *     {@link CtModul }
     *     
     */
    public CtModul getModule() {
        return module;
    }

    /**
     * Sets the value of the module property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtModul }
     *     
     */
    public void setModule(CtModul value) {
        this.module = value;
    }

    /**
     * Gets the value of the dozent property.
     * 
     * @return
     *     possible object is
     *     {@link CtDozent }
     *     
     */
    public CtDozent getDozent() {
        return dozent;
    }

    /**
     * Sets the value of the dozent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDozent }
     *     
     */
    public void setDozent(CtDozent value) {
        this.dozent = value;
    }

}
