//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.24 at 05:46:34 AM MESZ 
//


package dozenten;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_adresse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_adresse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anschrift" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="raumnr">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nummer" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="art" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="email">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="adresse" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_adresse", propOrder = {
    "anschrift",
    "raumnr",
    "tel",
    "email"
})
public class CtAdresse {

    @XmlElement(required = true)
    protected String anschrift;
    @XmlElement(required = true)
    protected CtAdresse.Raumnr raumnr;
    @XmlElement(required = true)
    protected CtAdresse.Tel tel;
    @XmlElement(required = true)
    protected CtAdresse.Email email;

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnschrift(String value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the raumnr property.
     * 
     * @return
     *     possible object is
     *     {@link CtAdresse.Raumnr }
     *     
     */
    public CtAdresse.Raumnr getRaumnr() {
        return raumnr;
    }

    /**
     * Sets the value of the raumnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAdresse.Raumnr }
     *     
     */
    public void setRaumnr(CtAdresse.Raumnr value) {
        this.raumnr = value;
    }

    /**
     * Gets the value of the tel property.
     * 
     * @return
     *     possible object is
     *     {@link CtAdresse.Tel }
     *     
     */
    public CtAdresse.Tel getTel() {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAdresse.Tel }
     *     
     */
    public void setTel(CtAdresse.Tel value) {
        this.tel = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link CtAdresse.Email }
     *     
     */
    public CtAdresse.Email getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAdresse.Email }
     *     
     */
    public void setEmail(CtAdresse.Email value) {
        this.email = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="adresse" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Email {

        @XmlAttribute
        protected String adresse;

        /**
         * Gets the value of the adresse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdresse() {
            return adresse;
        }

        /**
         * Sets the value of the adresse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdresse(String value) {
            this.adresse = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="nummer" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Raumnr {

        @XmlAttribute
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger nummer;

        /**
         * Gets the value of the nummer property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNummer() {
            return nummer;
        }

        /**
         * Sets the value of the nummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNummer(BigInteger value) {
            this.nummer = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nummer" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="art" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nummer"
    })
    public static class Tel {

        protected List<CtAdresse.Tel.Nummer> nummer;

        /**
         * Gets the value of the nummer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nummer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNummer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CtAdresse.Tel.Nummer }
         * 
         * 
         */
        public List<CtAdresse.Tel.Nummer> getNummer() {
            if (nummer == null) {
                nummer = new ArrayList<CtAdresse.Tel.Nummer>();
            }
            return this.nummer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="art" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="nr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Nummer {

            @XmlAttribute
            protected String art;
            @XmlAttribute
            protected String nr;

            /**
             * Gets the value of the art property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArt() {
                return art;
            }

            /**
             * Sets the value of the art property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArt(String value) {
                this.art = value;
            }

            /**
             * Gets the value of the nr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNr() {
                return nr;
            }

            /**
             * Sets the value of the nr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNr(String value) {
                this.nr = value;
            }

        }

    }

}
