//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 10:48:21 PM MESZ 
//


package dozenten;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_dozent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_dozent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adresse" type="{http://example.org/dozent}ct_adresse"/>
 *         &lt;element name="lehre" type="{http://example.org/dozent}ct_lehre"/>
 *         &lt;element name="newsticker" type="{http://example.org/dozent}ct_newsticker"/>
 *         &lt;element name="abonnenten" type="{http://example.org/dozent}ct_abonnenten"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_dozent", propOrder = {
    "titel",
    "adresse",
    "lehre",
    "newsticker",
    "abonnenten"
})
@XmlSeeAlso({
    Dozent.class
})
public class CtDozent {

    @XmlElement(required = true)
    protected String titel;
    @XmlElement(required = true)
    protected CtAdresse adresse;
    @XmlElement(required = true)
    protected CtLehre lehre;
    @XmlElement(required = true)
    protected CtNewsticker newsticker;
    @XmlElement(required = true)
    protected CtAbonnenten abonnenten;

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link CtAdresse }
     *     
     */
    public CtAdresse getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAdresse }
     *     
     */
    public void setAdresse(CtAdresse value) {
        this.adresse = value;
    }

    /**
     * Gets the value of the lehre property.
     * 
     * @return
     *     possible object is
     *     {@link CtLehre }
     *     
     */
    public CtLehre getLehre() {
        return lehre;
    }

    /**
     * Sets the value of the lehre property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtLehre }
     *     
     */
    public void setLehre(CtLehre value) {
        this.lehre = value;
    }

    /**
     * Gets the value of the newsticker property.
     * 
     * @return
     *     possible object is
     *     {@link CtNewsticker }
     *     
     */
    public CtNewsticker getNewsticker() {
        return newsticker;
    }

    /**
     * Sets the value of the newsticker property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtNewsticker }
     *     
     */
    public void setNewsticker(CtNewsticker value) {
        this.newsticker = value;
    }

    /**
     * Gets the value of the abonnenten property.
     * 
     * @return
     *     possible object is
     *     {@link CtAbonnenten }
     *     
     */
    public CtAbonnenten getAbonnenten() {
        return abonnenten;
    }

    /**
     * Sets the value of the abonnenten property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAbonnenten }
     *     
     */
    public void setAbonnenten(CtAbonnenten value) {
        this.abonnenten = value;
    }

}
