//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 10:48:21 PM MESZ 
//


package dozenten;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_lehre complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_lehre">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lehrgebiet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="schwerpunkte" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sprechzeit" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="veranstaltungen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_lehre", propOrder = {
    "lehrgebiet",
    "schwerpunkte",
    "url",
    "sprechzeit",
    "veranstaltungen"
})
public class CtLehre {

    @XmlElement(required = true)
    protected String lehrgebiet;
    protected String schwerpunkte;
    @XmlElement(required = true)
    protected String url;
    protected List<String> sprechzeit;
    @XmlElement(required = true)
    protected CtLehre.Veranstaltungen veranstaltungen;

    /**
     * Gets the value of the lehrgebiet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLehrgebiet() {
        return lehrgebiet;
    }

    /**
     * Sets the value of the lehrgebiet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLehrgebiet(String value) {
        this.lehrgebiet = value;
    }

    /**
     * Gets the value of the schwerpunkte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchwerpunkte() {
        return schwerpunkte;
    }

    /**
     * Sets the value of the schwerpunkte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchwerpunkte(String value) {
        this.schwerpunkte = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the sprechzeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sprechzeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSprechzeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSprechzeit() {
        if (sprechzeit == null) {
            sprechzeit = new ArrayList<String>();
        }
        return this.sprechzeit;
    }

    /**
     * Gets the value of the veranstaltungen property.
     * 
     * @return
     *     possible object is
     *     {@link CtLehre.Veranstaltungen }
     *     
     */
    public CtLehre.Veranstaltungen getVeranstaltungen() {
        return veranstaltungen;
    }

    /**
     * Sets the value of the veranstaltungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtLehre.Veranstaltungen }
     *     
     */
    public void setVeranstaltungen(CtLehre.Veranstaltungen value) {
        this.veranstaltungen = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bezeichnung"
    })
    public static class Veranstaltungen {

        protected List<Object> bezeichnung;

        /**
         * Gets the value of the bezeichnung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bezeichnung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBezeichnung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * 
         * 
         */
        public List<Object> getBezeichnung() {
            if (bezeichnung == null) {
                bezeichnung = new ArrayList<Object>();
            }
            return this.bezeichnung;
        }

    }

}
