//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.17 at 04:12:23 PM MESZ 
//


package dozenten;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dozenten package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dozenten
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dozent.Abonnenten.Abonnent }
     * 
     */
    public Dozent.Abonnenten.Abonnent createDozentAbonnentenAbonnent() {
        return new Dozent.Abonnenten.Abonnent();
    }

    /**
     * Create an instance of {@link Dozent }
     * 
     */
    public Dozent createDozent() {
        return new Dozent();
    }

    /**
     * Create an instance of {@link Dozent.Newsticker.Eintrag }
     * 
     */
    public Dozent.Newsticker.Eintrag createDozentNewstickerEintrag() {
        return new Dozent.Newsticker.Eintrag();
    }

    /**
     * Create an instance of {@link Dozent.Adresse }
     * 
     */
    public Dozent.Adresse createDozentAdresse() {
        return new Dozent.Adresse();
    }

    /**
     * Create an instance of {@link Dozent.Adresse.Tel.Nummer }
     * 
     */
    public Dozent.Adresse.Tel.Nummer createDozentAdresseTelNummer() {
        return new Dozent.Adresse.Tel.Nummer();
    }

    /**
     * Create an instance of {@link Dozent.Abonnenten }
     * 
     */
    public Dozent.Abonnenten createDozentAbonnenten() {
        return new Dozent.Abonnenten();
    }

    /**
     * Create an instance of {@link Dozent.Newsticker }
     * 
     */
    public Dozent.Newsticker createDozentNewsticker() {
        return new Dozent.Newsticker();
    }

    /**
     * Create an instance of {@link Dozent.Lehre }
     * 
     */
    public Dozent.Lehre createDozentLehre() {
        return new Dozent.Lehre();
    }

    /**
     * Create an instance of {@link Dozent.Adresse.Tel }
     * 
     */
    public Dozent.Adresse.Tel createDozentAdresseTel() {
        return new Dozent.Adresse.Tel();
    }

    /**
     * Create an instance of {@link Dozent.Adresse.Raum }
     * 
     */
    public Dozent.Adresse.Raum createDozentAdresseRaum() {
        return new Dozent.Adresse.Raum();
    }

    /**
     * Create an instance of {@link Dozent.Adresse.Email }
     * 
     */
    public Dozent.Adresse.Email createDozentAdresseEmail() {
        return new Dozent.Adresse.Email();
    }

    /**
     * Create an instance of {@link Dozent.Lehre.Veranstaltungen.List }
     * 
     */
    public Dozent.Lehre.Veranstaltungen.List createDozentLehreVeranstaltungenList() {
        return new Dozent.Lehre.Veranstaltungen.List();
    }

    /**
     * Create an instance of {@link Dozent.Lehre.Veranstaltungen }
     * 
     */
    public Dozent.Lehre.Veranstaltungen createDozentLehreVeranstaltungen() {
        return new Dozent.Lehre.Veranstaltungen();
    }

}
