//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.24 at 03:59:05 PM MESZ 
//


package dozenten;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dozenten package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dozenten
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtAdresse }
     * 
     */
    public CtAdresse createCtAdresse() {
        return new CtAdresse();
    }

    /**
     * Create an instance of {@link CtLehre.Veranstaltungen }
     * 
     */
    public CtLehre.Veranstaltungen createCtLehreVeranstaltungen() {
        return new CtLehre.Veranstaltungen();
    }

    /**
     * Create an instance of {@link CtLehre }
     * 
     */
    public CtLehre createCtLehre() {
        return new CtLehre();
    }

    /**
     * Create an instance of {@link CtAbonnenten }
     * 
     */
    public CtAbonnenten createCtAbonnenten() {
        return new CtAbonnenten();
    }

    /**
     * Create an instance of {@link CtNewsticker.Eintrag }
     * 
     */
    public CtNewsticker.Eintrag createCtNewstickerEintrag() {
        return new CtNewsticker.Eintrag();
    }

    /**
     * Create an instance of {@link CtLehre.Veranstaltungen.List }
     * 
     */
    public CtLehre.Veranstaltungen.List createCtLehreVeranstaltungenList() {
        return new CtLehre.Veranstaltungen.List();
    }

    /**
     * Create an instance of {@link Dozent }
     * 
     */
    public Dozent createDozent() {
        return new Dozent();
    }

    /**
     * Create an instance of {@link CtNewsticker }
     * 
     */
    public CtNewsticker createCtNewsticker() {
        return new CtNewsticker();
    }

}
